# Full Example: https://github.com/geekan/MetaGPT/blob/main/config/config2.example.yaml
# Reflected Code: https://github.com/geekan/MetaGPT/blob/main/metagpt/config2.py
# Config Docs: https://docs.deepwisdom.ai/main/en/guide/get_started/configuration.html
llm:
  api_type: "openai"  # or azure / ollama / groq etc.
  model: "gpt-3.5-turbo-ca"  # or gpt-3.5-turbo
  base_url: "https://api.chatanywhere.tech"  # or forward url / other llm url
  api_key: "sk-VRFrw99K4ju0G1fwoh0kJ4UcDiejvxEgWCu8iHDmHqf1OJfk"